name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  cmdstanVersion: "2.34.1"

jobs:
  build:
    name: Package tests and linting
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: 3.10
          cache: pip
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cmdstan
          key: ${{ env.cmdstanVersion }}
      - name: Install cmdstanpy
        run: python -m cmdstanpy.install_cmdstan --version ${{ env.cmdstanVersion }}
      - name: Run the models
        run: make
